#!/bin/bash
# new-rule.sh - Interactive creation of a new git message rule

set -e

GITMSG_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$GITMSG_ROOT/lib/common.sh"
source "$GITMSG_ROOT/lib/ask.sh"

echo "=== Creating a new Git Message Rule ==="
echo ""

# Step 1: Ask for rule description
echo "Step 1: Rule Description"
echo "------------------------"
echo "Please describe your git commit message rule in natural language."
echo "You can include examples of good and bad commit messages."
echo ""

RULE_DESCRIPTION=""
while IFS= read -r line; do
    if [ -z "$line" ]; then
        break
    fi
    RULE_DESCRIPTION="${RULE_DESCRIPTION}${line}"$'\n'
done

echo ""
echo "Rule description received (${#RULE_DESCRIPTION} characters)"
echo ""

# Step 2: Ask for rule name
MAX_RENAME_ATTEMPTS=3
rename_attempt=0

while true; do
    echo "Step 2: Rule Name"
    echo "-----------------"
    read -p "Name this rule (alphanumeric, hyphen, underscore only): " rule_name

    if ! validate_rule_name "$rule_name"; then
        echo "Invalid rule name. Use only letters, numbers, hyphens, and underscores."
        continue
    fi

    # Step 3: Check for duplicates
    if check_duplicate_rule "$rule_name"; then
        echo ""
        echo "A rule named '$rule_name' already exists."

        # Use AskUserQuestion pattern (simulated in shell)
        echo ""
        echo "What would you like to do?"
        echo "  1) Override it - Replace existing rule with this one"
        echo "  2) Rename mine - Choose a different name"
        echo ""
        read -p "Select [1-2]: " choice

        case $choice in
            1)
                # Override
                echo "Will override existing rule '$rule_name'"
                break
                ;;
            2)
                # Rename
                rename_attempt=$((rename_attempt + 1))
                if [ $rename_attempt -ge $MAX_RENAME_ATTEMPTS ]; then
                    # Auto-generate unique name
                    rule_name=$(generate_unique_name "$rule_name")
                    echo "Maximum rename attempts reached. Auto-generated unique name: $rule_name"
                    break
                fi
                # Continue loop to ask for new name
                continue
                ;;
            *)
                echo "Invalid choice. Please try again."
                continue
                ;;
        esac
    else
        break
    fi
done

echo ""
echo "Rule name: $rule_name"
echo ""

# Step 4: Author/Email storage
echo "Step 4: Author/Email Configuration"
echo "-----------------------------------"
echo "How should author and email be stored for this rule?"
echo ""
echo "  1) From ~/.gitconfig - Auto-fill from git config"
echo "  2) Manual input - Enter author and email manually"
echo "  3) Not stored - Prompt on each commit"
echo ""
read -p "Select [1-3]: " auth_choice

AUTHOR_NAME=""
AUTHOR_EMAIL=""
STORE_AUTHOR=false
STORE_EMAIL=false

case $auth_choice in
    1)
        # Read from gitconfig
        AUTHOR_NAME=$(get_git_config "user.name")
        AUTHOR_EMAIL=$(get_git_config "user.email")
        echo "  Found: $AUTHOR_NAME <$AUTHOR_EMAIL>"

        # Ask what to store
        echo ""
        echo "What to store?"
        ask_yes_no "Store author name?" "y" && STORE_AUTHOR=true
        ask_yes_no "Store email?" "y" && STORE_EMAIL=true

        if [ "$STORE_AUTHOR" = false ]; then
            AUTHOR_NAME=""
        fi
        if [ "$STORE_EMAIL" = false ]; then
            AUTHOR_EMAIL=""
        fi
        ;;
    2)
        # Manual input
        read -p "  Author name: " AUTHOR_NAME
        read -p "  Author email: " AUTHOR_EMAIL
        STORE_AUTHOR=true
        STORE_EMAIL=true
        ;;
    3)
        # Not stored
        AUTHOR_NAME=""
        AUTHOR_EMAIL=""
        ;;
esac

echo ""

# Step 5: Lint rule generation
echo "Step 5: Linting Configuration"
echo "-----------------------------"
ask_yes_no "Generate lint rule for this rule? (saved to rules/$rule_name/)" "y"
GENERATE_LINT=$?

echo ""

# Step 6: Interactive mode
echo "Step 6: Interactive Mode"
echo "------------------------"
ask_yes_no "Should this rule require interactive prompts by default?" "y"
INTERACTIVE=$?

echo ""

# Step 7: Generate rule structure
echo "Step 7: Generating Rule"
echo "-----------------------"

create_rule_structure "$rule_name"
RULE_DIR="$GITMSG_ROOT/rules/$rule_name"

# Create rule.md from description
cat > "$RULE_DIR/rule.md" << EOF
# $rule_name Git Commit Message Rule

## Overview
$RULE_DESCRIPTION

## Generated by gitmsg skill
Created: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
Interactive: $([ "$INTERACTIVE" -eq 0 ] && echo "yes" || echo "no")
Lint enabled: $([ "$GENERATE_LINT" -eq 0 ] && echo "yes" || echo "no")
EOF

# Create rule.json
cat > "$RULE_DIR/rule.json" << EOF
{
  "name": "$rule_name",
  "version": "1.0.0",
  "description": "Auto-generated rule from user input",
  "created_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "interactive": $([ "$INTERACTIVE" -eq 0 ] && echo "true" || echo "false"),
  "lint_enabled": $([ "$GENERATE_LINT" -eq 0 ] && echo "true" || echo "false"),
  "metadata": {
    "author": $([ -n "$AUTHOR_NAME" ] && echo "\"$AUTHOR_NAME\"" || echo "null"),
    "email": $([ -n "$AUTHOR_EMAIL" ] && echo "\"$AUTHOR_EMAIL\"" || echo "null")
  }
}
EOF

# Create metadata.json
cat > "$RULE_DIR/metadata.json" << EOF
{
  "name": "$rule_name",
  "version": "1.0.0",
  "created_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "author": $([ -n "$AUTHOR_NAME" ] && echo "\"$AUTHOR_NAME\"" || echo "null"),
  "email": $([ -n "$AUTHOR_EMAIL" ] && echo "\"$AUTHOR_EMAIL\"" || echo "null"),
  "description": "Auto-generated rule",
  "interactive": $([ "$INTERACTIVE" -eq 0 ] && echo "true" || echo "false"),
  "lint_enabled": $([ "$GENERATE_LINT" -eq 0 ] && echo "true" || echo "false")
}
EOF

# Create basic template
cat > "$RULE_DIR/template.md" << 'EOF'
{type}: {subject}

{body}

{footer}
EOF

# Create basic pattern.yaml
if [ "$GENERATE_LINT" -eq 0 ]; then
    cat > "$RULE_DIR/pattern.yaml" << 'EOF'
# Commit Message Linting Patterns
# Customize these patterns for your rule

header_pattern: '^(?P<type>\w+):\s*(?P<subject>.+)$'

validation:
  subject_max_length: 72
  body_min_lines: 0
  max_line_length: 100
EOF

    # Copy and adapt lint.sh from RTOS
    cp "$GITMSG_ROOT/rules/RTOS/lint.sh" "$RULE_DIR/lint.sh"
    chmod +x "$RULE_DIR/lint.sh"
fi

# Create examples directory placeholders
mkdir -p "$RULE_DIR/examples"
cat > "$RULE_DIR/examples/good.md" << EOF
# Good Commit Message Examples for $rule_name Rule

## Example 1
\`\`\`
feat: add new feature

Description of what was added and why.
\`\`\`
EOF

cat > "$RULE_DIR/examples/bad.md" << EOF
# Bad Commit Message Examples for $rule_name Rule

## ❌ Example 1
\`\`\`
added new thing

Not in imperative mood, no details.
\`\`\`
EOF

echo "✅ Rule created successfully!"
echo ""
echo "Rule location: $RULE_DIR"
echo ""
echo "Next steps:"
echo "  1. Review and edit: $RULE_DIR/rule.md"
echo "  2. Customize template: $RULE_DIR/template.md"
echo "  3. Update patterns: $RULE_DIR/pattern.yaml"
echo "  4. Add examples: $RULE_DIR/examples/"
echo ""
echo "To set as default for this repo:"
echo "  gitmsg --default-rule $rule_name"
echo ""
echo "To use:"
echo "  gitmsg --rule $rule_name"
