#!/usr/bin/env python3
"""Interactive CLI to capture git-message rules."""

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional


class RuleCreator:
    def __init__(self, skill_dir: Path) -> None:
        self.skill_dir = skill_dir
        self.rules_dir = skill_dir / "rules"
        self.rules_dir.mkdir(parents=True, exist_ok=True)

    def run(self, preset_name: Optional[str] = None) -> None:
        print("🚀 Git Message Rule Creator\n")

        rule_spec = self._get_rule_specification()
        rule_name = preset_name or self._get_rule_name()
        rule_name = self._handle_duplicate(rule_name)
        author_config = self._get_author_config()
        generate_lint = self._ask_lint_generation()
        interactive = self._ask_interactive_mode()
        self._create_rule(rule_name, rule_spec, author_config, generate_lint, interactive)

        print(f"\n✅ Rule '{rule_name}' created successfully!")
        print(f"📁 Location: {self.rules_dir / rule_name}")

    def _get_rule_specification(self) -> str:
        print("📝 Describe your git message rule:")
        print("   (You can include examples, paste existing rules, etc.)")
        print("   (Press Ctrl+D on empty line to finish)\n")

        lines = []
        try:
            while True:
                line = input()
                lines.append(line)
        except EOFError:
            pass

        return "\n".join(lines).strip()

    def _get_rule_name(self) -> str:
        while True:
            name = input("\n🏷️  Name your rule: ").strip()
            if name and name.replace("-", "").replace("_", "").isalnum():
                return name
            print("   ⚠️  Name must be alphanumeric (with - or _)")

    def _handle_duplicate(self, name: str) -> str:
        rule_path = self.rules_dir / name
        if not rule_path.exists():
            return name

        print(f"\n⚠️  A rule named '{name}' already exists!")
        print("   What would you like to do?")
        print("   [1] Override it")
        print("   [2] Choose a different name")
        choice = input("   Choice (1/2): ").strip()

        if choice == "1":
            return name
        if choice == "2":
            return self._get_rule_name()

        counter = 1
        while (self.rules_dir / f"{name}-{counter}").exists():
            counter += 1
        new_name = f"{name}-{counter}"
        print(f"   ℹ️  Auto-renamed to: {new_name}")
        return new_name

    def _get_author_config(self) -> Dict[str, Any]:
        print("\n👤 Author/Email Configuration:")
        print("   Do you want to store default author/email?")

        config: Dict[str, Any] = {}

        from_file = input("   Load from file? (y/N): ").strip().lower() == "y"
        if from_file:
            default_path = str(Path.home() / ".gitconfig")
            file_path = input(f"   File path [{default_path}]: ").strip() or default_path
            config["from_file"] = file_path
            return config

        if input("   Store author? (y/N): ").strip().lower() == "y":
            author = input("   Author name: ").strip()
            config["author"] = author

        if input("   Store email? (y/N): ").strip().lower() == "y":
            email = input("   Email: ").strip()
            config["email"] = email

        if not config:
            config["fetch_on_commit"] = True

        return config

    def _ask_lint_generation(self) -> bool:
        print("\n🔍 Lint Rules:")
        response = input("   Generate lint rules? (Y/n): ").strip().lower()
        return response != "n"

    def _ask_interactive_mode(self) -> bool:
        print("\n💬 Interaction Mode:")
        response = input("   Enable interactive mode by default? (Y/n): ").strip().lower()
        return response != "n"

    def _create_rule(
        self,
        name: str,
        spec: str,
        author_config: Dict[str, Any],
        generate_lint: bool,
        interactive: bool,
    ) -> None:
        rule_dir = self.rules_dir / name
        rule_dir.mkdir(parents=True, exist_ok=True)

        config = {
            "name": name,
            "specification": spec,
            "author_config": author_config,
            "interactive": interactive,
            "lint_enabled": generate_lint,
            "created_at": self._get_timestamp(),
        }

        (rule_dir / "config.json").write_text(json.dumps(config, indent=2, ensure_ascii=False), encoding="utf-8")
        (rule_dir / "template.txt").write_text("# Template will be generated by LLM\n", encoding="utf-8")

        if generate_lint:
            (rule_dir / "lint-rules.json").write_text("[]", encoding="utf-8")

        metadata = {
            "status": "pending_llm_processing",
            "needs_template": True,
            "needs_lint_rules": generate_lint,
        }

        (rule_dir / ".metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    def _get_timestamp(self) -> str:
        return datetime.now().isoformat()


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a new git message rule")
    parser.add_argument("--rule-name", help="Preset rule name")
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    skill_dir = script_dir.parent

    creator = RuleCreator(skill_dir)
    creator.run(preset_name=args.rule_name)


if __name__ == "__main__":
    main()
